[package]
authors = ["Zeke Sonxx <zeke@zekesonxx.com>"]
name = "deviltool"
version = "0.1.0"

[dependencies]
byteorder = "1.1.0"
clap = "2.26.0"
filetime = "0.1.10"
image = "0.15.0"
nom = "3.2.0"
time = "0.1.38"
